spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: c##interviewnexus
    password: InterviewNexus2024
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: oracle
